# -*- coding: utf-8 -*-
"""stable-diffusion-2-example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GP4pbyqhmbodAj1AaPVp_umDt7j-UFFq
"""

!pip install transformers

!pip install diffusers

from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")

pip install diffusers transformers accelerate scipy safetensors

!pip install torch

pip install torchvision

!pip install accelerate

import torch
import torchvision
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler

model_id = "stabilityai/stable-diffusion-2"

# Use the Euler scheduler here instead
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

while True:
  prompt = input("Enter a sentence to classify its sentiment (type 'exit' to quit): ")
  if prompt == "exit":
    break
  image = pipe(prompt).images[0]
  image.save("astronaut_rides_horse.png")
  image.show()